name: housing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=2.1.1
  - scikit-learn=1.3.1
  - pydantic=2.11.7
  - uvicorn=0.34.3
  - fastapi=0.115.14
  - python-dotenv=1.1.1
  - ipykernel=6.29.5
  - requests=2.32.4
  - matplotlib=3.5.0
  - seaborn=0.13.2
  - pytest=8.4.1
